[tools]
go = "1.25"

[tasks.install]
alias = "i"
run = [
    "mise install",
    "go get fyne.io/fyne/v2@latest",
    "go install fyne.io/tools/cmd/fyne@latest",
]

[tasks.build]
description = "Build"
alias = "b"
run = "go build ."

[tasks.start]
description = "Start"
alias = "s"
run = "go run ."

[tasks.demo]
description = "Run fyne demo app"
run = "go run fyne.io/demo@latest"
