[tools]
go = "1.25"

[tasks.install]
alias = "i"
run = [
    "mise install",
    "go mod download",
    "go install fyne.io/tools/cmd/fyne@latest",
]

[tasks.build]
description = "Build"
alias = "b"
run = "fyne package -os darwin -icon icon.png"

[tasks.start]
description = "Start"
alias = "s"
depends = "build"
run = "open roger.app"

[tasks.demo]
description = "Run fyne demo app"
run = "go run fyne.io/demo@latest"
